export const RankingDef = [
    {
      name: 'Interbrand_BestGlobalBrands',
      display_name: 'Interbrand - Best Global Brands (2021)',
      description: `Interbrand has been the world’s leading brand consultancy, for over 40 years – having pioneered iconic work and forged many of the brand building tools that are now commonplace.`,
      link: 'https://interbrand.com/best-global-brands/',
      data:[
        {
            name: "Apple",
            symbol: "AAPL",
            rank: 1,
            link: "https://interbrand.com/best-global-brands/apple/",
        },
        {
            name: "Amazon",
            symbol: "AMZN",
            rank: 2,
            link: "https://interbrand.com/best-global-brands/amazon/",
        },
        {
            name: "Microsoft",
            symbol: "MSFT",
            rank: 3,
            link: "https://interbrand.com/best-global-brands/microsoft/",
        },
        {
            name: "Google",
            symbol: "GOOG",
            rank: 4,
            link: "https://interbrand.com/best-global-brands/google/",
        },
        {
            name: "Samsung",
            symbol: "SSNLF",
            rank: 5,
            link: "https://interbrand.com/best-global-brands/samsung/",
        },
        {
            name: "Coca-Cola",
            symbol: "KO",
            rank: 6,
            link: "https://interbrand.com/best-global-brands/coca-cola/",
        },
        {
            name: "Toyota",
            symbol: "TM",
            rank: 7,
            link: "https://interbrand.com/best-global-brands/toyota/",
        },
        {
            name: "Mercedes-Benz",
            symbol: "DMLRY",
            rank: 8,
            link: "https://interbrand.com/best-global-brands/mercedes-benz/",
        },
        {
            name: "McDonald's",
            symbol: "MCD",
            rank: 9,
            link: "https://interbrand.com/best-global-brands/mcdonalds/",
        },
        {
            name: "Disney",
            symbol: "DIS",
            rank: 10,
            link: "https://interbrand.com/best-global-brands/disney/",
        },
        {
            name: "Nike",
            symbol: "NKE",
            rank: 11,
            link: "https://interbrand.com/best-global-brands/nike/",
        },
        {
            name: "BMW",
            symbol: "BMWYY",
            rank: 12,
            link: "https://interbrand.com/best-global-brands/bmw/",
        },
        {
            name: "Louis Vuitton",
            symbol: "LVMUY",
            rank: 13,
            link: "https://interbrand.com/best-global-brands/louis-vuitton/",
        },
        {
            name: "Tesla",
            symbol: "TSLA",
            rank: 14,
            link: "https://interbrand.com/best-global-brands/tesla/",
        },
        {
            name: "Facebook",
            symbol: "FB",
            rank: 15,
            link: "https://interbrand.com/best-global-brands/facebook/",
        },
        {
            name: "Cisco",
            symbol: "CSCO",
            rank: 16,
            link: "https://interbrand.com/best-global-brands/cisco/",
        },
        {
            name: "Intel",
            symbol: "INTC",
            rank: 17,
            link: "https://interbrand.com/best-global-brands/intel/",
        },
        {
            name: "IBM",
            symbol: "IBM",
            rank: 18,
            link: "https://interbrand.com/best-global-brands/ibm/",
        },
        {
            name: "Instagram",
            symbol: "FB",
            rank: 19,
            link: "https://interbrand.com/best-global-brands/instagram/",
        },
        {
            name: "SAP",
            symbol: "SAP",
            rank: 20,
            link: "https://interbrand.com/best-global-brands/sap/",
        },
        {
            name: "Adobe",
            symbol: "ADBE",
            rank: 21,
            link: "https://interbrand.com/best-global-brands/adobe/",
        },
        {
            name: "Chanel",
            symbol: "-",
            rank: 22,
            link: "https://interbrand.com/best-global-brands/chanel/",
        },
        {
            name: "Hermès",
            symbol: "HESAY",
            rank: 23,
            link: "https://interbrand.com/best-global-brands/hermes/",
        },
        {
            name: "J.P. Morgan",
            symbol: "JPM",
            rank: 24,
            link: "https://interbrand.com/best-global-brands/j-p-morgan/",
        },
        {
            name: "Honda",
            symbol: "HMC",
            rank: 25,
            link: "https://interbrand.com/best-global-brands/honda/",
        },
        {
            name: "Youtube",
            symbol: "GOOG",
            rank: 26,
            link: "https://interbrand.com/best-global-brands/youtube/",
        },
        {
            name: "IKEA",
            symbol: "-",
            rank: 27,
            link: "https://interbrand.com/best-global-brands/ikea/",
        },
        {
            name: "Pepsi",
            symbol: "PEP",
            rank: 28,
            link: "https://interbrand.com/best-global-brands/pepsi/",
        },
        {
            name: "UPS",
            symbol: "UPS",
            rank: 29,
            link: "https://interbrand.com/best-global-brands/ups/",
        },
        {
            name: "American Express",
            symbol: "AXP",
            rank: 30,
            link: "https://interbrand.com/best-global-brands/american-express/",
        },
        {
            name: "GE",
            symbol: "GE",
            rank: 31,
            link: "https://interbrand.com/best-global-brands/ge/",
        },
        {
            name: "Accenture",
            symbol: "ACN",
            rank: 32,
            link: "https://interbrand.com/best-global-brands/accenture/",
        },
        {
            name: "Gucci",
            symbol: "KER.PA",
            rank: 33,
            link: "https://interbrand.com/best-global-brands/gucci/",
        },
        {
            name: "Allianz",
            symbol: "ALV.DE",
            rank: 34,
            link: "https://interbrand.com/best-global-brands/allianz/",
        },
        {
            name: "Hyundai",
            symbol: "HYMTF",
            rank: 35,
            link: "https://interbrand.com/best-global-brands/hyundai/",
        },
        {
            name: "Netflix",
            symbol: "NFLX",
            rank: 36,
            link: "https://interbrand.com/best-global-brands/netflix/",
        },
        {
            name: "Budweiser",
            symbol: "BUD",
            rank: 37,
            link: "https://interbrand.com/best-global-brands/budweiser/",
        },
        {
            name: "Salesforce",
            symbol: "CRM",
            rank: 38,
            link: "https://interbrand.com/best-global-brands/salesforce/",
        },
        {
            name: "Visa",
            symbol: "V",
            rank: 39,
            link: "https://interbrand.com/best-global-brands/visa/",
        },
        {
            name: "Nescafé",
            symbol: "NSRGY",
            rank: 40,
            link: "https://interbrand.com/best-global-brands/nescafe/",
        },
        {
            name: "Sony",
            symbol: "SONY",
            rank: 41,
            link: "https://interbrand.com/best-global-brands/sony/",
        },
        {
            name: "PayPal",
            symbol: "PYPL",
            rank: 42,
            link: "https://interbrand.com/best-global-brands/paypal/",
        },
        {
            name: "H&M",
            symbol: "HM-B.ST",
            rank: 43,
            link: "https://interbrand.com/best-global-brands/hm/",
        },
        {
            name: "Pampers",
            symbol: "PG",
            rank: 44,
            link: "https://interbrand.com/best-global-brands/pampers/",
        },
        {
            name: "Zara",
            symbol: "IDEXF",
            rank: 45,
            link: "https://interbrand.com/best-global-brands/zara/",
        },
        {
            name: "Audi",
            symbol: "AUDVF",
            rank: 46,
            link: "https://interbrand.com/best-global-brands/audi/",
        },
        {
            name: "Volkswagen",
            symbol: "VWAGY",
            rank: 47,
            link: "https://interbrand.com/best-global-brands/volkswagen/",
        },
        {
            name: "AXA",
            symbol: "CS.PA",
            rank: 48,
            link: "https://interbrand.com/best-global-brands/axa/",
        },
        {
            name: "adidas",
            symbol: "ADS.DE",
            rank: 49,
            link: "https://interbrand.com/best-global-brands/adidas/",
        },
        {
            name: "Mastercard",
            symbol: "MA",
            rank: 50,
            link: "https://interbrand.com/best-global-brands/mastercard/",
        },
        {
            name: "Starbucks",
            symbol: "SBUX",
            rank: 51,
            link: "https://interbrand.com/best-global-brands/starbucks/",
        },
        {
            name: "Ford",
            symbol: "F",
            rank: 52,
            link: "https://interbrand.com/best-global-brands/ford/",
        },
        {
            name: "L’Oréal",
            symbol: "or.pa",
            rank: 53,
            link: "https://interbrand.com/best-global-brands/loreal/",
        },
        {
            name: "Citi",
            symbol: "C",
            rank: 54,
            link: "https://interbrand.com/best-global-brands/citi/",
        },
        {
            name: "Goldman Sachs",
            symbol: "GS",
            rank: 55,
            link: "https://interbrand.com/best-global-brands/goldman-sachs/",
        },
        {
            name: "eBay",
            symbol: "EBAY",
            rank: 56,
            link: "https://interbrand.com/best-global-brands/ebay/",
        },
        {
            name: "Philips",
            symbol: "PHG",
            rank: 57,
            link: "https://interbrand.com/best-global-brands/philips/",
        },
        {
            name: "Porsche",
            symbol: "POAHY",
            rank: 58,
            link: "https://interbrand.com/best-global-brands/porsche/",
        },
        {
            name: "Nissan",
            symbol: "NSANY",
            rank: 59,
            link: "https://interbrand.com/best-global-brands/nissan/",
        },
        {
            name: "Siemens",
            symbol: "SIEGY",
            rank: 60,
            link: "https://interbrand.com/best-global-brands/siemens/",
        },
        {
            name: "Gillette",
            symbol: "PG",
            rank: 61,
            link: "https://interbrand.com/best-global-brands/gillette/",
        },
        {
            name: "Nestlé",
            symbol: "NSRGY",
            rank: 62,
            link: "https://interbrand.com/best-global-brands/nestle/",
        },
        {
            name: "HP",
            symbol: "HPQ",
            rank: 63,
            link: "https://interbrand.com/best-global-brands/hp/",
        },
        {
            name: "HSBC",
            symbol: "HSBC",
            rank: 64,
            link: "https://interbrand.com/best-global-brands/hsbc/",
        },
        {
            name: "Danone",
            symbol: "BN.PA",
            rank: 65,
            link: "https://interbrand.com/best-global-brands/danone/",
        },
        {
            name: "Spotify",
            symbol: "SPOT",
            rank: 66,
            link: "https://interbrand.com/best-global-brands/spotify/",
        },
        {
            name: "3M",
            symbol: "MMM",
            rank: 67,
            link: "https://interbrand.com/best-global-brands/3m/",
        },
        {
            name: "Colgate",
            symbol: "CL",
            rank: 68,
            link: "https://interbrand.com/best-global-brands/colgate/",
        },
        {
            name: "Morgan Stanley",
            symbol: "MS",
            rank: 69,
            link: "https://interbrand.com/best-global-brands/morgan-stanley/",
        },
        {
            name: "Nintendo",
            symbol: "NTDOY",
            rank: 70,
            link: "https://interbrand.com/best-global-brands/nintendo/",
        },
        {
            name: "LEGO",
            symbol: "-",
            rank: 71,
            link: "https://interbrand.com/best-global-brands/lego/",
        },
        {
            name: "Kellogg’s",
            symbol: "K",
            rank: 72,
            link: "https://interbrand.com/best-global-brands/kelloggs/",
        },
        {
            name: "Cartier",
            symbol: "-",
            rank: 73,
            link: "https://interbrand.com/best-global-brands/cartier/",
        },
        {
            name: "Santander",
            symbol: "SAN",
            rank: 74,
            link: "https://interbrand.com/best-global-brands/santander/",
        },
        {
            name: "FedEx",
            symbol: "FDX",
            rank: 75,
            link: "https://interbrand.com/best-global-brands/fedex/",
        },
        {
            name: "Ferrari",
            symbol: "RACE",
            rank: 76,
            link: "https://interbrand.com/best-global-brands/ferrari/",
        },
        {
            name: "Dior",
            symbol: "CDI.PA",
            rank: 77,
            link: "https://interbrand.com/best-global-brands/dior/",
        },
        {
            name: "Corona",
            symbol: "STZ",
            rank: 78,
            link: "https://interbrand.com/best-global-brands/corona/",
        },
        {
            name: "Canon",
            symbol: "CAJ",
            rank: 79,
            link: "https://interbrand.com/best-global-brands/canon/",
        },
        {
            name: "DHL",
            symbol: "DPW.DE",
            rank: 80,
            link: "https://interbrand.com/best-global-brands/dhl/",
        },
        {
            name: "Jack Daniel’s",
            symbol: "BF-B",
            rank: 81,
            link: "https://interbrand.com/best-global-brands/jack-daniels/",
        },
        {
            name: "Caterpillar",
            symbol: "CAT",
            rank: 82,
            link: "https://interbrand.com/best-global-brands/caterpillar/",
        },
        {
            name: "LinkedIn",
            symbol: "MSFT",
            rank: 83,
            link: "https://interbrand.com/best-global-brands/linkedin/",
        },
        {
            name: "Hewlett Packard Enterprise",
            symbol: "HPE",
            rank: 84,
            link: "https://interbrand.com/best-global-brands/hewlett-packard-enterprise/",
        },
        {
            name: "Huawei",
            symbol: "-",
            rank: 85,
            link: "https://interbrand.com/best-global-brands/huawei/",
        },
        {
            name: "Kia",
            symbol: "HYMTF",
            rank: 86,
            link: "https://interbrand.com/best-global-brands/kia/",
        },
        {
            name: "Johnson & Johnson",
            symbol: "JNJ",
            rank: 87,
            link: "https://interbrand.com/best-global-brands/johnson-johnson/",
        },
        {
            name: "Panasonic",
            symbol: "PCRFY",
            rank: 88,
            link: "https://interbrand.com/best-global-brands/panasonic/",
        },
        {
            name: "Heineken",
            symbol: "HEINY",
            rank: 89,
            link: "https://interbrand.com/best-global-brands/heineken/",
        },
        {
            name: "John Deere",
            symbol: "DE",
            rank: 90,
            link: "https://interbrand.com/best-global-brands/john-deere/",
        },
        {
            name: "Zoom",
            symbol: "ZM",
            rank: 91,
            link: "https://interbrand.com/best-global-brands/zoom/",
        },
        {
            name: "Tiffany & Co.",
            symbol: "LVMUY",
            rank: 92,
            link: "https://interbrand.com/best-global-brands/tiffany-co/",
        },
        {
            name: "KFC",
            symbol: "YUM",
            rank: 93,
            link: "https://interbrand.com/best-global-brands/kfc/",
        },
        {
            name: "Prada",
            symbol: "PRDSY",
            rank: 94,
            link: "https://interbrand.com/best-global-brands/prada/",
        },
        {
            name: "Hennessy",
            symbol: "LVMUY",
            rank: 95,
            link: "https://interbrand.com/best-global-brands/hennessy/",
        },
        {
            name: "MINI",
            symbol: "BMWYY",
            rank: 96,
            link: "https://interbrand.com/best-global-brands/mini/",
        },
        {
            name: "Burberry",
            symbol: "BURBY",
            rank: 97,
            link: "https://interbrand.com/best-global-brands/burberry/",
        },
        {
            name: "Land Rover",
            symbol: "TTM",
            rank: 98,
            link: "https://interbrand.com/best-global-brands/land-rover/",
        },
        {
            name: "Uber",
            symbol: "UBER",
            rank: 99,
            link: "https://interbrand.com/best-global-brands/uber/",
        },
        {
            name: "Sephora",
            symbol: "LVMUY",
            rank: 100,
            link: "https://interbrand.com/best-global-brands/sephora/",
        }
      ]
    }
  ]