name: FetchGoogleTrendData

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Copy github ci files to ci-folder
      run: |-
        cp -r ./.github/fetch_google_trend ./ci-folder
    - name: Checkout gh-pages branch
      run: |-
        git checkout gh-pages
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./ci-folder/requirements.txt
    - name: Fetch google-trend-data
      env:
        AF_URL: ${{ secrets.AF_URL }}
        AF_TOKEN: ${{ secrets.AF_TOKEN }}
        GOOGLE_TREND_API_LIST: ${{ secrets.GOOGLE_TREND_API_LIST }}
      run: |-
        python ./ci-folder/fetch_google_trend.py
    - name: Delete ci-folder
      run: |-
        rm -rf ./ci-folder
    - name: Add norn-data and push it
      run: |-
        git config --global user.name "zmcx16-bot"
        git config --global user.email "zmcx16-bot@zmcx16.moe"
        git config --global pull.ff only
        git pull
        git reset --soft HEAD~1
        git add ./norn-data/\* && git commit -m "updated website & google-trend-data"
        git push -f
