name: FetchNornData

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 11,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Copy github ci files to ci-folder
      run: |-
        cp -r ./.github/fetch_norn_data ./ci-folder
    - name: Checkout gh-pages branch
      run: |-
        git checkout gh-pages
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./ci-folder/requirements.txt
    - name: Fetch norn-data
      env:
        MARKET_URL: ${{ secrets.MARKET_URL }}
        MARKET_TOKEN: ${{ secrets.MARKET_TOKEN }}
      run: |-
        python ./ci-folder/fetch_norn_data.py
    - name: Delete ci-folder
      run: |-
        rm -rf ./ci-folder
    - name: Add norn-data and push it
      run: |-
        git config --global user.name "zmcx16-bot"
        git config --global pull.ff only
        git pull
        git reset --soft HEAD~1
        git add ./norn-data/\* && git commit -m "updated website & norn-data"
        git push -f
    - name: Checkout zmcx16.github.io
      uses: actions/checkout@master
      with: 
        repository: zmcx16/zmcx16.github.io
        token: ${{ secrets.ACTIONS_TOKEN }}
        path: ./zmcx16.github.io
    - name: Copy indusrty-table.json & push zmcx16.github.io
      run: |-
        cp -f ./norn-data/indusrty-table.json ./zmcx16.github.io/
        cd ./zmcx16.github.io
        git config --global user.name "zmcx16-bot"
        git add indusrty-table.json && git commit -m "updated indusrty-table.json"
        git push
